version: 2.1

# Define jobs for the workflow
jobs:
  # Job for saying hello
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  # Job for SonarQube analysis
  sonarqube:
    working_directory: ~/build
    docker:
      - image: sonarsource/sonar-scanner-cli
    resource_class: small
    steps:
      - checkout
      - run:
          name: Run SonarQube Analysis
          command: |
            SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
            echo "Sonar branch value is: $SONAR_BRANCH"
            # It's safer not to echo sensitive tokens like SONAR_TOKEN
            sonar-scanner \
              -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
              -Dsonar.organization="$SONAR_ORG" \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.exclusions="**/android/**,**/ios/**" \
              -Dsonar.login="$SONAR_TOKEN" \
              -Dsonar.branch.name="$SONAR_BRANCH" \
              -Dsonar.sources="."

  # Job for Newman API testing
  newman-tests:
    docker:
      - image: postman/newman:latest
    steps:
      - checkout
      # Verify Postman Collection Exists with correct path
      - run:
          name: Verify Postman Collection Exists
          command: |
            if [ ! -f customerpaymentsportal/tests/postman_collection.json ]; then
              echo "Error: Postman collection file is missing"; exit 1;
            fi
      - run:
          name: Run Newman Tests
          command: newman run customerpaymentsportal/tests/postman_collection.json

# Orchestrate jobs using workflows
workflows:
  version: 2
  full-pipeline:
    jobs:
      - say-hello
      - sonarqube
      - newman-tests
